spring:
  application:
    name: spring-cloud-ribbon #服务发现者的名字
  #模板引擎的配置
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8764 #端口为8764
#Eureka设置
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/